use test
GO

CREATE TABLE Authors(
	AuthorId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AuthorName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Categories(
	CategoryId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CategoryName nvarchar(20) NOT NULL UNIQUE
);

CREATE TABLE Publishers(
	PublisherId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PublisherName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Alerts(
	ISBN NVARCHAR(15) NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	AlertDate DATETIME NOT NULL DEFAULT GETDATE(),
	AlertType NVARCHAR(50) NOT NULL,
	AlertDescription NVARCHAR(50) NOT NULL
);

CREATE TABLE Books(
	BookId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ISBN NVARCHAR(15) NOT NULL UNIQUE,
	Title NVARCHAR(50) NOT NULL,
	CategoryId INT NOT NULL,
	AuthorId INT NOT NULL,
	PublisherId INT NOT NULL,
	Page INT NOT NULL,
	Price MONEY NOT NULL,
	Discount TINYINT NOT NULL DEFAULT 0,
	DiscountAvailable BIT NOT NULL DEFAULT 1,
	Stock INT NOT NULL,
	Available BIT NOT NULL DEFAULT 1,
	CONSTRAINT CHK_Discount CHECK (Discount < 100),
	CONSTRAINT CHK_Price CHECK (Price > 0),
	CONSTRAINT FK_BooksCategories FOREIGN KEY (CategoryId)
	REFERENCES Categories(CategoryId),
	CONSTRAINT FK_BooksAuthors FOREIGN KEY (AuthorId)
	REFERENCES Authors(AuthorId),
	CONSTRAINT FK_BooksPublishers FOREIGN KEY (PublisherId)
	REFERENCES Publishers(PublisherId)
);

CREATE TABLE ListMonthly(
	ListItemId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BookId INT NOT NULL FOREIGN KEY REFERENCES Books(BookId)
);

CREATE TABLE Users(
	UserId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Email NVARCHAR(50) NOT NULL UNIQUE,
	PasswordHash BINARY(64) NOT NULL,
	Salt UNIQUEIDENTIFIER NOT NULL,
	ResetToken NVARCHAR(64) NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	Phone NVARCHAR(20) NOT NULL,
	AltPhone NVARCHAR(20),
	Address NVARCHAR(20) NOT NULL,
	City NVARCHAR(20) NOT NULL,
	State NVARCHAR(20) NOT NULL,
	LastLogin DATETIME
);

CREATE TABLE Roles(
	RoleId INT NOT NULL PRIMARY KEY,
	RoleName NVARCHAR(20) NOT NULL,
);

INSERT INTO Roles (RoleId, RoleName)
     VALUES
           (0, 'admin'),
           (1, 'customer');

CREATE TABLE UserRoles(
	RoleId INT NOT NULL DEFAULT 1 FOREIGN KEY REFERENCES Roles(RoleId),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(UserId)
);

CREATE TABLE Carts(
	CartId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UserId INT NOT NULL,
	DateCreated DATETIME NOT NULL,
	CheckedOut BIT NOT NULL DEFAULT 0,
	TotalPrice MONEY,
	CONSTRAINT FK_CartsUsers FOREIGN KEY (UserId)
	REFERENCES Users(UserId)
);

CREATE TABLE CartItems(
	CartItemId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CartId INT NOT NULL,
	BookId INT NOT NULL,
	Quantity INT NOT NULL,
	UnitPrice MONEY NOT NULL,
	CONSTRAINT FK_CartItemsCarts FOREIGN KEY (CartId)
	REFERENCES Carts(CartId),
	CONSTRAINT FK_CartItemsBooks FOREIGN KEY (BookId)
	REFERENCES Books(BookId)
);

CREATE TABLE Orders(
	OrderId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UserId INT NOT NULL,
	TotalPrice MONEY,
	Status NVARCHAR(50) NOT NULL,
	DateCreated DATETIME NOT NULL,
	CONSTRAINT FK_OrdersUsers FOREIGN KEY (UserId)
	REFERENCES Users(UserId)
);

CREATE TABLE OrderItems(
	OrderItemId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	OrderId INT NOT NULL,
	BookId INT NOT NULL,
	Quantity INT NOT NULL,
	UnitPrice MONEY NOT NULL,
	CONSTRAINT FK_OrderItemsOrders FOREIGN KEY (OrderId)
	REFERENCES Orders(OrderId),
	CONSTRAINT FK_OrderItemsBooks FOREIGN KEY (BookId)
	REFERENCES Books(BookId)
);

CREATE TABLE ShippingInfo(
	ShippingId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	OrderId INT NOT NULL,
	TrackingNumber NVARCHAR(50),
	ShippingCost MONEY NOT NULL,
	ShippingAddress NVARCHAR(50),
	CONSTRAINT FK_ShippingInfoOrders FOREIGN KEY (OrderId)
	REFERENCES Orders(OrderId)
);
